services:

  db:
    image: postgres:16
    container_name: autorent_db
    volumes:
      - C:/containers/database/autorent/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"